apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: sabnzbd
    spec:
      dockerImageRepository: jameseckersall/sabnzbd
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      creationTimestamp: null
      generation: 4
      labels:
        app: sabnzbd
      name: sabnzbd
    spec:
      replicas: 1
      selector:
        app: sabnzbd
        deploymentconfig: sabnzbd
      strategy:
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: sabnzbd
            deploymentconfig: sabnzbd
        spec:
          containers:
          - image: jameseckersall/sabnzbd
            imagePullPolicy: Always
            readinessProbe:
              initialDelaySeconds: 5
              httpGet:
                path: /
                port: 8080
              timeoutSeconds: 5
            livenessProbe:
              initialDelaySeconds: 5
              httpGet:
                path: /
                port: 8080
              timeoutSeconds: 30
            name: sabnzbd
            ports:
            - containerPort: 8080
              protocol: TCP
            env:
            - name: SITE_URL
              value: ${SITE_URL}
            resources: {}
            terminationMessagePath: /dev/termination-log
            volumeMounts:
            - mountPath: /downloads
              name: sabnzbd-downloads
            - mountPath: /config
              name: sabnzbd-config
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - hostPath:
              path: ${CONFIG_HOST_PATH}
            name: sabnzbd-config
          - hostPath:
              path: ${DOWNLOADS_HOST_PATH}
            name: sabnzbd-downloads
      test: false
      triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChange: {}
  - apiVersion: v1
    kind: Route
    metadata:
      creationTimestamp: null
      labels:
        app: sabnzbd
      name: sabnzbd
    spec:
      host: ${SITE_URL}
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: sabnzbd
        weight: 100
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        app: sabnzbd
      name: sabnzbd
    spec:
      ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        app: sabnzbd
        deploymentconfig: sabnzbd
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
parameters:
- name: SITE_URL
  value: sabnzbd.example.com
  required: true
- name: CONFIG_HOST_PATH
  value: /tmp
  required: true
- name: DOWNLOADS_HOST_PATH
  value: /tmp
  required: true
